name: CI

# Run on all pushes (except release/* and tags) and on every PR
on:
  push:
    branches-ignore:
      - 'release/**'
    tags-ignore:
      - 'v*'
  pull_request: {}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.20.2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build all
        run: npm run build

