# name: Deploy to Test

# on:
#   push:
#     branches:
#       - 'test'

# env:
#   TEST_GCP_PROJECT: ${{ vars.IM_TEST_PROJECT_ID }}
#   TEST_FIREBASE_PROJECT: ${{ vars.IM_TEST_PROJECT_ID }}
#   NODE_VERSION: 22.13.0

# jobs:
#   # ─────────── 1) Build & Deploy NestJS API to App Engine (Test) ───────────
#   deploy-server-test:
#     name: ▶️ API → Test
#     environment: Test
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

#       - name: Use Node.js ${{ env.NODE_VERSION }}
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ env.NODE_VERSION }}

#       - name: Install dependencies
#         run: npm ci && npm install -g nx@12.3.6

#       - name: Generate Angular environment (test)
#         run: npx ts-node ./util/generate_environment.ts generate test
#         env:
#           INVOLVEMINT_SETTINGS: ${{ secrets.INVOLVEMINT_TEST_SETTINGS_SERVER }}

#       - name: Build API (test)
#         run: |
#           export NODE_OPTIONS=--openssl-legacy-provider
#           nx run-many --target=build --projects=api --configuration=test --skip-nx-cache

#       - name: Authenticate to GCP
#         uses: google-github-actions/auth@v2
#         with:
#           credentials_json: ${{ secrets.GCP_SA_KEY }}

#       - name: Deploy API to App Engine (Test)
#         run: |
#           # Strip off "refs/heads/" prefix and sanitize
#           BRANCH=${github.sha}
#           BRANCH=${BRANCH,,};                   # lowercase
#           BRANCH=${BRANCH//[^a-z0-9-]/-};       # replace invalid chars
#           BRANCH=${BRANCH:0:63}               # trim to 63 chars
#           # if it starts with a digit or hyphen, prefix a letter
#           [[ $BRANCH =~ ^[0-9-] ]] && BRANCH="v$BRANCH"
#           CALCVERSION="test-${BRANCH}"             # e.g. "test-feature-xyz"

#           gcloud config set project ${{ env.TEST_GCP_PROJECT }}
#           gcloud app deploy app.yaml \
#             --stop-previous-version \
#             --quiet \
#             --version=${CALCVERSION} \
#             --verbosity=debug \

#   deploy-client:
#     name: ▶️ Client → Test
#     runs-on: ubuntu-latest
#     environment: Test
#     needs: deploy-server-test
#     steps:
#       - uses: actions/checkout@v3

#       - name: Use Node.js ${{ env.NODE_VERSION }}
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ env.NODE_VERSION }}

#       - name: Install dependencies
#         run: npm ci && npm install -g nx@12.3.6 && npm install -g firebase-tools@13.29.0

#       - name: Generate Angular environment (test)
#         run: npx ts-node ./util/generate_environment.ts generate test
#         env:
#           INVOLVEMINT_SETTINGS: ${{ secrets.INVOLVEMINT_TEST_SETTINGS_CLIENT }}

#       - name: Build Client (test)
#         run: |
#           export NODE_OPTIONS=--openssl-legacy-provider
#           nx run-many --target=build --projects=involvemint --configuration=test --skip-nx-cache

#       - name: Authenticate to GCP & Firebase
#         uses: google-github-actions/auth@v2
#         with:
#           credentials_json: ${{ secrets.GCP_SA_KEY }}

#       - name: Deploy Client to Firebase
#         run: |
#           firebase use ${{ env.TEST_FIREBASE_PROJECT }}
#           firebase deploy --message "Test deploy: ${{ github.sha }}"
