export const enum InvolvemintOrchestrations {
    changeMaker = 'changeMaker',
    chat = 'chat',
    credit = 'credit',
    enrollment = 'enrollment',
    epAdmin = 'ep-admin',
    epApplication = 'ep-application',
    exchangePartner = 'exchangePartner',
    handle = 'handle',
    offer = 'offer',
    passport = 'passport',
    poi = 'poi',
    project = 'project',
    request = 'request',
    servePartner = 'servePartner',
    spAdmin = 'sp-admin',
    spApplication = 'sp-application',
    storage = 'storage',
    transaction = 'transaction',
    user = 'user',
    voucher = 'voucher',
    activityPost = "activityPost",
    comment = "comment"
}
